import dotenv from "dotenv";
dotenv.config();


// Gemini API Keys — round-robin rotation
export const GEMINI_API_KEYS = [
    process.env.GEMINI_API_KEY_1 || process.env.GEMINI_API_KEY || null,
    process.env.GEMINI_API_KEY_2 || null,
    process.env.GEMINI_API_KEY_3 || null,
].filter(Boolean);

export const MONGO_URI = process.env.MONGO_URI;

// ── Remote vertical database ──────────────────────────────────────────────
// The `remoteJobs` collection is written by a separate process
// (ejg-remote-scraper) that points at the hosted Atlas cluster. The German
// product, by contrast, is routinely developed against a local mongod.
//
// Pointing both at one URI forces a false choice: either local development
// loses the German test data, or the remote vertical reads an empty local
// collection while the scraper fills Atlas — which is exactly the split that
// made the API report ~1.7k jobs while Atlas held ~3.7k.
//
// So the remote vertical gets its own URI. Unset, it falls back to MONGO_URI,
// which is the correct behaviour in production where both are the same cluster.
export const REMOTE_MONGO_URI = process.env.REMOTE_MONGO_URI || process.env.MONGO_URI;

/** Host of a Mongo URI with credentials stripped — safe to log. */
export function describeMongoUri(uri) {
    if (!uri) return '(unset)';
    try {
        const withoutCreds = uri.replace(/\/\/[^@]*@/, '//');
        const { protocol, host, pathname } = new URL(withoutCreds);
        return `${protocol}//${host}${pathname}`;
    } catch {
        return '(unparseable)';
    }
}


// Resend email config
export const RESEND_API_KEY = process.env.RESEND_API_KEY;


// ── Signup Gate ───────────────────────────────────────────────────────────
// FREE_VIEW_LIMIT: distinct full-job views before gating. NEVER expose to client.
// NEW_VISITOR_RATE_LIMIT_PER_HOUR: anti-bypass rate limit on new visitor creation.
// VISITOR_IP_SALT: REQUIRED random string for hashing IPs.
//   Generate: node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
// FRONTEND_ORIGIN: needed for CORS with credentials (cookies + JWT).
export const FREE_VIEW_LIMIT = Number(process.env.FREE_VIEW_LIMIT) || 20;
// ANONYMOUS_VIEW_LIMIT: JD views an anonymous (non-signed-up) visitor gets per
// week before the signup gate. Deliberately lower than FREE_VIEW_LIMIT — the
// gate on the /:id/full route passes this to shouldGate() for anonymous users,
// while other callers keep using FREE_VIEW_LIMIT. NEVER expose to client.
export const ANONYMOUS_VIEW_LIMIT = Number(process.env.ANONYMOUS_VIEW_LIMIT) || 5;
export const NEW_VISITOR_RATE_LIMIT_PER_HOUR = Number(process.env.NEW_VISITOR_RATE_LIMIT_PER_HOUR) || 20;
export const VISITOR_IP_SALT = process.env.VISITOR_IP_SALT;
export const FRONTEND_ORIGIN = process.env.FRONTEND_ORIGIN || 'http://localhost:5173';

// ── Auto-publish confidence bands ─────────────────────────────────────────
// The scraper routes accepted jobs by the AI's confidence that the posting does
// NOT require German (job *quality* is already handled by the pre-AI filters):
//   >= AUTO_PUBLISH_THRESHOLD   → Status 'active' immediately, admin confirms later
//   >= MANUAL_REVIEW_THRESHOLD  → Status 'pending_review', admin must approve
//   <  MANUAL_REVIEW_THRESHOLD  → auto-rejected as too ambiguous
// Both are env-tunable so the bands can be tightened without a deploy. Raising
// AUTO_PUBLISH_THRESHOLD is the safe direction — it sends more jobs to humans.
export const AUTO_PUBLISH_THRESHOLD = Number(process.env.AUTO_PUBLISH_THRESHOLD) || 0.85;
export const MANUAL_REVIEW_THRESHOLD = Number(process.env.MANUAL_REVIEW_THRESHOLD) || 0.60;

// ── SEO ───────────────────────────────────────────────────────────────────
// Canonical public origin, used for <link rel=canonical>, OG tags, JSON-LD
// and sitemap URLs. Must be the real public site — NOT the API origin, or
// Google will index the wrong host. Distinct from FRONTEND_ORIGIN, which is
// a CORS allow-list value and points at localhost in development.
export const SITE_URL = (process.env.SITE_URL || 'https://englishjobsgermany.com').replace(/\/$/, '');

// ── Premium early access ──────────────────────────────────────────────────
// One shared 100%-off code, redeemable once per user (enforced in
// premium.routes.js via subscription history). Sent in the welcome email to
// new signups and via scripts/send-premium-invite.js to existing users.
// Personal one-time invite codes (EJG-XXXX-XXXX) are generated by the
// /join-waitlist endpoint alongside this shared code.
export const BETA_PROMO_CODE = (process.env.BETA_PROMO_CODE || 'BETA2026').toUpperCase();

// ── Google OAuth ──────────────────────────────────────────────────────────
// Web Client ID from Google Cloud Console. Same value as VITE_GOOGLE_CLIENT_ID.
// We use the ID-token flow, so no client secret is needed.
export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;

if (!VISITOR_IP_SALT) {
    console.warn('[env] ⚠️  VISITOR_IP_SALT not set — IP hashing will be insecure.');
}
if (!GOOGLE_CLIENT_ID) {
    console.warn('[env] ⚠️  GOOGLE_CLIENT_ID not set — Google login will not work.');
}